In [1]:
import pandas as pd
import csv
import tkinter as tk
from tkinter import *

In [2]:
def Update_Price():
    file = open("stockprice.csv","a")
    date = ent_Date.get()
    ent_Date.delete(0,END)
    ticker = ent_Ticker.get()
    ent_Ticker.delete(0,END)
    price = ent_Price.get()
    ent_Price.delete(0,END)
    newrecord = str(date + "," + ticker + "," + price + "\n")
    file.write(newrecord)
    file.close()
    
# Tạo cửa sổ cập nhật giá chứng khoán
win_Price = Tk()
win_Price.title("Cập nhật giá CK")
win_Price.geometry("300x150")

lb_Date = Label(win_Price, text = "Ngày ")
lb_Date.place(x=30, y=10)

lb_Ticker = Label(win_Price, text = "Mã CK ")
lb_Ticker.place(x=30, y=40)

lb_Price = Label (win_Price, text = "Giá: ")
lb_Price.place(x=30,y=70)

ent_Date = Entry(win_Price, width = 15)
ent_Date.place (x=100, y = 10)
#ent_Date.focus()

ent_Ticker = Entry(win_Price, width = 15)
ent_Ticker.place (x=100, y=40)
ent_Ticker.focus()

ent_Price = Entry(win_Price, width = 15)
ent_Price.place(x= 100, y=70)

but_Update = Button(win_Price, text = "Update", command = Update_Price)
but_Update.place(x=100, y=100)




win_Price.mainloop()

In [3]:
sprice= pd.read_csv("stockprice.csv")
sprice

          Date  Sticker   Price
0     14/03/23      HPG    20300
1     14/03/23      HPG    20300
2     14/03/23      HPG    20300
3     14/03/23      HSG    15400
4     14/03/23      NKG    15200
5     14/03/23      ABB     7800
6     14/03/23      ACT    15000
7     14/03/23      NT2    15000
8     14/03/23      NT2    15000
9     14/03/23      AGT     4000
10    14/03/23      HPG    20100
11    14/03/23      HSG    15000
12    14/03/23      NKG    14000
13  2023/03/14      NNT    23000
14  2023/03/14      HHP    30000

In [ ]:
file = open("stockprice.csv","a")
date = input("ngày: ")
ticker = input("mã ck: ")
price = input("giá: ")
newrecord = str(date + "," + ticker + "," + price + "\n")
file.write(newrecord)
file.close()

In [ ]:
sprice= pd.read_csv("stockprice.csv")
sprice

In [ ]:
import datetime as dt
current_date = dt.date.today()
print(current_date)

class Stock:
    def __init__(self):
        self.ticker = ""
        self.qty = 0
        self.cost_price =0
        self.market_price =0
class Stock_Price:
    def __init__(self):
        self.date = current_date
        self.ticker =""
        self.price =0
class Stock_Trade:
    def __init__(self):
        self.date = current_date
        self.buy_sell = "B"
        self.ticker = ""
        self.qty = 0
        self.price = 0
        self.fee = 0
        self.tax = 0
class Cashflow:
    def __init_(self):
        self.date = current_date
        self.flow = "in"
        self.amount = 0
        self.note =""

In [ ]:
class Stock_Price:
    def __init__(self):
        self.date = current_date
        self.ticker =""
        self.price =0
    def set(self):
        self.date = input("Nhập ngày: ")
        self.ticker = input("Nhập mã CK: ")
        self.price = int(input("Giá: "))

ticker = Stock_Price()
ticker.set()

In [ ]:
import csv
filename = "stockprice.csv"
fields =[]
rows = []